name: mdigestenv
channels:
- conda-forge
- schrodinger
dependencies:
# required for building docs
  - python==3.11
  - pip
  - numpy
  - scipy
  - numba
  - python-louvain==0.15
  - pymol-open-source
  - MDAnalysis
  - pandas
  - seaborn
  - mdtraj
  - pyemma
  - silx
  - nglview
  - networkx

 #<=1.24.3
 #>= 1.11.1
 #>=0.57.1