name: test_pypi
channels:
- conda-forge
- schrodinger
dependencies:
# required for building docs
  - python=3.10
  - pip
  - numpy<=1.24.3
  - scipy>=1.10.0
  - numba==0.56.4
  - python-louvain==0.15
  - pymol-open-source
  - pandas
  - seaborn
  - mdtraj
  - pyemma
  - MDAnalysis
  - silx
  - nglview
  - networkx
